version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    ports:
      - "5050:80"
  api:
    container_name: api
    build: 
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api/node_modules
      - ./api/:/app
    restart: on-failure
    command: npm start
    links:
      - db:db
    depends_on:
      - db
    environment:
      - API_PORT
      - API_HOST
    ports: 
      - "5000:5000"
    
